/*
 * Validate src/scripts/inference/mel.js against Python golden vectors
 * (generated by export_wakeword.py) and the exported ONNX classifier.
 *
 * Run from fable/:  node ml/wakeword/validate_mel.mjs
 * Gates: mel dB MAE < 0.1 dB · JS-mel -> ONNX score |Δ| < 0.01 vs keras.
 */

import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { melSpectrogram, N_FRAMES, N_MELS } from '../../src/scripts/inference/mel.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const goldenDir = path.join(here, 'golden');
const modelPath = path.join(here, '../../public/models/wakeword-clf.onnx');

let ort = null;
try {
  ort = await import('onnxruntime-web');
} catch {
  console.log('onnxruntime-web not installed yet — skipping score parity check');
}
const session = ort ? await ort.InferenceSession.create(modelPath) : null;

let failed = false;
for (const file of readdirSync(goldenDir).filter((f) => f.endsWith('.json'))) {
  const g = JSON.parse(readFileSync(path.join(goldenDir, file), 'utf8'));
  const mel = melSpectrogram(Float32Array.from(g.pcm));

  // mel parity: golden melDb is (80, 301)
  let sum = 0;
  let max = 0;
  for (let m = 0; m < N_MELS; m++) {
    for (let f = 0; f < N_FRAMES; f++) {
      const d = Math.abs(mel.data[m * N_FRAMES + f] - g.melDb[m][f]);
      sum += d;
      if (d > max) max = d;
    }
  }
  const mae = sum / (N_MELS * N_FRAMES);
  const melOk = mae < 0.1;

  let scoreLine = '';
  if (session) {
    const input = new ort.Tensor('float32', mel.data, [1, N_MELS, N_FRAMES]);
    const out = await session.run({ [session.inputNames[0]]: input });
    const score = out[session.outputNames[0]].data[0];
    const dScore = Math.abs(score - g.score);
    const scoreOk = dScore < 0.01;
    scoreLine = ` · score js=${score.toFixed(4)} keras=${g.score.toFixed(4)} Δ=${dScore.toExponential(1)} ${scoreOk ? 'OK' : 'FAIL'}`;
    if (!scoreOk) failed = true;
  }

  console.log(`${g.id}: mel MAE=${mae.toFixed(4)} dB max=${max.toFixed(3)} ${melOk ? 'OK' : 'FAIL'}${scoreLine}`);
  if (!melOk) failed = true;
}

if (failed) {
  console.error('VALIDATION FAILED');
  process.exit(1);
}
console.log('PASS');
